/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      // ── CSS-variable-based colors (resolved per theme scope) ──────────────
      colors: {
        'primary':                  'var(--c-primary)',
        'on-primary':               'var(--c-on-primary)',
        'primary-container':        'var(--c-primary-container)',
        'on-primary-container':     'var(--c-on-primary-container)',
        'primary-fixed':            'var(--c-primary-fixed)',
        'primary-fixed-dim':        'var(--c-primary-fixed-dim)',
        'on-primary-fixed':         'var(--c-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--c-on-primary-fixed-variant)',
        'secondary':                'var(--c-secondary)',
        'on-secondary':             'var(--c-on-secondary)',
        'secondary-container':      'var(--c-secondary-container)',
        'on-secondary-container':   'var(--c-on-secondary-container)',
        'secondary-fixed':          'var(--c-secondary-fixed)',
        'secondary-fixed-dim':      'var(--c-secondary-fixed-dim)',
        'on-secondary-fixed':       'var(--c-on-secondary-fixed)',
        'on-secondary-fixed-variant':'var(--c-on-secondary-fixed-variant)',
        'tertiary':                 'var(--c-tertiary)',
        'on-tertiary':              'var(--c-on-tertiary)',
        'tertiary-container':       'var(--c-tertiary-container)',
        'on-tertiary-container':    'var(--c-on-tertiary-container)',
        'tertiary-fixed':           'var(--c-tertiary-fixed)',
        'tertiary-fixed-dim':       'var(--c-tertiary-fixed-dim)',
        'surface':                  'var(--c-surface)',
        'surface-dim':              'var(--c-surface-dim)',
        'surface-bright':           'var(--c-surface-bright)',
        'surface-tint':             'var(--c-surface-tint)',
        'surface-container-lowest': 'var(--c-surface-container-lowest)',
        'surface-container-low':    'var(--c-surface-container-low)',
        'surface-container':        'var(--c-surface-container)',
        'surface-container-high':   'var(--c-surface-container-high)',
        'surface-container-highest':'var(--c-surface-container-highest)',
        'surface-variant':          'var(--c-surface-variant)',
        'on-surface':               'var(--c-on-surface)',
        'on-surface-variant':       'var(--c-on-surface-variant)',
        'inverse-surface':          'var(--c-inverse-surface)',
        'inverse-on-surface':       'var(--c-inverse-on-surface)',
        'outline':                  'var(--c-outline)',
        'outline-variant':          'var(--c-outline-variant)',
        'background':               'var(--c-background)',
        'on-background':            'var(--c-on-background)',
        'error':                    'var(--c-error)',
        'on-error':                 'var(--c-on-error)',
        'error-container':          'var(--c-error-container)',
        'on-error-container':       'var(--c-on-error-container)',
      },
      // ── Border radius matching Stitch designs ──────────────────────────────
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      // ── Spacing matching both Stitch spacing scales ────────────────────────
      spacing: {
        '2xs':            '0.125rem',
        'xs':             '0.25rem',
        'sm':             '0.5rem',
        'md':             '0.75rem',
        'lg':             '1rem',
        'xl':             '1.5rem',
        '2xl':            '2rem',
        'gutter':         '0.5rem',
        'margin':         '1rem',
        'space-2xs':      '0.125rem',
        'space-xs':       '0.25rem',
        'space-sm':       '0.5rem',
        'space-md':       '0.75rem',
        'space-lg':       '1rem',
        'space-xl':       '1.5rem',
        'space-2xl':      '2rem',
        'space-3xl':      '3rem',
        'pane-gutter':    '0.75rem',
        'terminal-row':   '1.25rem',
        'inset-telemetry':'0.875rem',
        'cell-padding-y': '0.25rem',
        'cell-padding-x': '0.5rem',
      },
      // ── Font families ──────────────────────────────────────────────────────
      fontFamily: {
        // Quantum Console (Alice/Bob)
        'display-lg':  ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'body-lg':     ['Geist', 'Inter', 'sans-serif'],
        'body-md':     ['Geist', 'Inter', 'sans-serif'],
        'body-sm':     ['Geist', 'Inter', 'sans-serif'],
        'label-md':    ['Geist', 'Inter', 'sans-serif'],
        'label-sm':    ['Geist', 'Inter', 'sans-serif'],
        'code-lg':     ['Geist Mono', 'JetBrains Mono', 'monospace'],
        'code-md':     ['Geist Mono', 'JetBrains Mono', 'monospace'],
        'code-sm':     ['Geist Mono', 'JetBrains Mono', 'monospace'],
        // Eve Console — JetBrains Mono everywhere
        'headline-xl':        ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['JetBrains Mono', 'monospace'],
        'label-caps':         ['JetBrains Mono', 'monospace'],
        // Aliases for Stitch classes
        'clash':  ['Sora', 'sans-serif'],
        'general':['Geist', 'Inter', 'sans-serif'],
        'mono-soc':['IBM Plex Mono', 'Geist Mono', 'monospace'],
      },
      // ── Font size tokens ───────────────────────────────────────────────────
      fontSize: {
        'display-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':       ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md':       ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm':       ['14px', { lineHeight: '20px', letterSpacing: '0.02em',  fontWeight: '600' }],
        'headline-xl':       ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile':['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg':           ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md':           ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-sm':           ['11px', { lineHeight: '16px', fontWeight: '400' }],
        'code-lg':           ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'code-md':           ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm':           ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
        'label-md':          ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm':          ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-caps':        ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      // ── Keyframes ──────────────────────────────────────────────────────────
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: 1 },
          '50%':       { opacity: 0.4 },
        },
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 2s cubic-bezier(0.4,0,0.6,1) infinite',
      },
    },
  },
  plugins: [],
};
